name: Build Vendor Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Maven
      # explicitly use maven 3.6.3. At newer versions of Maven HTTP mirrors are blocken. We need to switch to HTTPS only mirrors first.
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.6.3

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name:  Maven Build
      run: |
          cd de.yatta.softwarevendor.demo/de.yatta.softwarevendor.demo.releng
          mvn package

    - name: 'Upload Client Artifacts' # upload client artifacts github internally; we might us this later for deployment
      uses: actions/upload-artifact@v2
      with:
        name: de.yatta.softwarevendor.demo.site
        path: code.yatta.softwarevendor.demo/de.yatta.softwarevendor.demo.site/target/repository/**
        retention-days: 3
